version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6

    branches:
      only:
        - master

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - cache-{{ checksum "Pipfile.lock" }}
          - cache-

      - run:
          name: Install dependencies
          command: pipenv sync --dev

      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache

      - run:
          name: Lint code
          command: pipenv run lint

      - run:
          name: Run tests
          command: pipenv run test
